version: "3.9"
services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=NaniAvalone
      - MONGO_INITDB_ROOT_PASSWORD=tHYR@ji!2xcDDkK
    ports:
    - "27017:27017"
    volumes:
    -  /home/marianne/code/mongo_db/data/db